import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_Component/Home/Navbar/Navbar";
import Footer from "./_Component/Footer/Footer";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <div className="max-w-[1440px] mx-auto px-4 sm:px-6 md:px-10 lg:px-16">
        </div>
        <Navbar />
        {/* <Mainslider /> */}
        {children}
        <Toaster
          position="top-center"
          reverseOrder={false}
          containerStyle={{
            top: 20,
            left: "50%",
            transform: "translateX(-50%)",
          }}
        />
        <Footer />
      </body>
    </html>
  );
}
