import "./globals.css";
import Navbar from "./_Component/Home/Navbar/Navbar";
import Footer from "./_Component/Footer/Footer";
import { Toaster } from "react-hot-toast";
import MySessionProvider from "./_Component/SessionProvider/MySessionProvider";
import FavProvider from "./_Component/Home/Navbar/favContext/favContext";
import { AuthProvider } from "@/Context/AuthContext";
import { Metadata } from "next";
import { CartContextProvider } from "@/Context/CartContext";

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
  icons: {
    icon: "/freshcart-logo.svg ",
  },
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <MySessionProvider>
            <CartContextProvider>
              <FavProvider>
                <Navbar />
                <div className="max-w-[1440px] mx-auto px-4 sm:px-6 md:px-10 lg:px-16">
                  {children}
                  <Toaster position="top-center" />
                </div>
                <Footer />
              </FavProvider>
            </CartContextProvider>
          </MySessionProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
